# Generated by Django 2.0.7 on 2018-08-01 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='number',
        ),
    ]
